// <auto-generated />
using System;
using Lab5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Lab5.Models.Learner", b =>
                {
                    b.Property<int>("LearnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MajorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LearnerID");

                    b.HasIndex("MajorID");

                    b.ToTable("Learners");

                    b.HasData(
                        new
                        {
                            LearnerID = 1,
                            EnrollmentDate = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Carson",
                            LastName = "Alexander",
                            MajorID = 1
                        },
                        new
                        {
                            LearnerID = 2,
                            EnrollmentDate = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Meredith",
                            LastName = "Alonso",
                            MajorID = 2
                        });
                });

            modelBuilder.Entity("Lab5.Models.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MajorID");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            MajorID = 1,
                            MajorName = "IT"
                        },
                        new
                        {
                            MajorID = 2,
                            MajorName = "Economics"
                        },
                        new
                        {
                            MajorID = 3,
                            MajorName = "Mathematics"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Learner", b =>
                {
                    b.HasOne("Lab5.Models.Major", "Major")
                        .WithMany("Learners")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Lab5.Models.Major", b =>
                {
                    b.Navigation("Learners");
                });
#pragma warning restore 612, 618
        }
    }
}
